### ISSUE TITLE
Look into DB MGEN repeats in Parsed data

### ISSUE THREAD

**Issue by EmotiBit** [EmotiBit/ofxEmotiBit#17]

**Comment by EmotiBit** [comment]
[multiple_MGEN_DB_Issue.zip](https://github.com/EmotiBit/ofxEmotiBit/files/3998945/multiple_MGEN_DB_Issue.zip)

**Comment by EmotiBit** [comment]
![image](https://user-images.githubusercontent.com/46901652/71423717-37e63500-2659-11ea-9790-fb7588db25fe.png)
![image](https://user-images.githubusercontent.com/46901652/71423724-459bba80-2659-11ea-8b56-dfaa24f41842.png)

**Comment by nitin710** [comment]
deprecated
