### ISSUE TITLE
Firmware Installer does not work with Feather M0 (Mac M1 Ventura 13.1)

### ISSUE THREAD

**Issue by JaeminBBQ** [EmotiBit/ofxEmotiBit#213]
**Describe the bug**
The Firmware Installer is not detecting the EmotiBit with Feather M0.

**Expected behavior**
Detect EmotiBit and install the firmware onto the EmotiBit.

**Additional details**
- EmotiBit software version: 1.8.1
- EmotiBit firmware version: 1.8.1-TA
- EmotiBit hardware version: V04a
- OS version:

**To Reproduce**
1. Open Firmware Installer
2. Press Space
3. Press reset on EmotiBit (While not in hib)
4. Connect EmotiBit to computer with data capable cable

**Screenshots**

| Open Firmware Installer | Press Space | Connect EmotiBit |
| ------------------------ | ------------ | ----------------- |
| <img width="575" alt="Screenshot 2023-06-12 at 12 25 36 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/8d2531ec-e8da-4203-8cb1-5e54f956e093"> | <img width="645" alt="Screenshot 2023-06-12 at 12 30 55 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/2075b15a-4f58-4547-bcf0-74d1dfe36c2e"> | <img width="644" alt="Screenshot 2023-06-12 at 12 31 32 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/73e6cbe5-6e34-427a-946c-bde6c7e30c08"> |

| when you plug in the Feather M0 into the mac, how does the new port appear in Arduino IDE Tools > Port? |
| --- |
| <img width="298" alt="Screenshot 2023-06-18 at 6 42 18 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/c5f0f920-fe71-474d-9c37-c95479fd1a97"> |

1.8.1.fix-firmwareInstallerAppleSiliconFix.2
- https://github.com/EmotiBit/ofxEmotiBit/releases/tag/untagged-5e1dce81185f3d35f02c

Results
| Open Firmware Installer | Press Space | Connect EmotiBit | GUI screen after connecting EmotiBit |
| ------------------------ | ------------ | ----------------- | -------------------------------------- |
| <img width="565" alt="Screenshot 2023-06-18 at 6 52 20 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/c9c75d52-6e25-4316-9b65-efb95bd38f67"> | <img width="645" alt="Screenshot 2023-06-18 at 6 52 52 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/38648630-0570-4521-95d4-03da7f9723e7"> | <img width="638" alt="Screenshot 2023-06-18 at 6 53 25 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/000ae656-7a26-413f-8353-669773cf568a"> | <img width="1005" alt="Screenshot 2023-06-18 at 6 53 41 PM" src="https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/b9de88b5-8c3f-4e49-a4b9-759d21e4a9a3"> |

Still not detecting.

<!--- Dont forget to label the bug appropriately

**Comment by nitin710** [comment]
Huh, looks the the driver in Apple silicon Macs is either 
1. Not exposing VID/PID in device info
2. VID/PID are not getting registered by the drivers.

Anyway, looks like this can be solved by a software patch. Ill add the fix in #212

**Comment by nitin710** [comment]
The Feather M0 shows up as `usbmodem`
and the Feather esp32 shows up as `usbserial` (Apart from the `SLAB_USBtoUART` port)

The solution could require checking for the keyword `usmodem` in the serial name

**Comment by nitin710** [comment]
Looks like something in the ofxSerial library may not be handling the information as presented by the drivers in M1 macs: https://github.com/bakercp/ofxSerial/blob/7a02ff97c02fdd038e367806128415ed794e48c7/libs/serial/src/impl/list_ports/list_ports_osx.cc#L241-L277

**Comment by JaeminBBQ** [comment]
`When you get the chance, can you share what the PID/VID are for the Adafruit Feather M0, as shown in this link:`
https://www.keychron.com/pages/how-to-check-pid-and-vid-in-your-mac

| Screenshot | Description |
| ----------- | ------------ |
| ![Screenshot 2023-06-19 at 3 58 28 PM](https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/7fc2bbaa-86e7-4155-9e73-596aba016684) | Screenshot of Adafruit Feather M0 in USB |

**Comment by JaeminBBQ** [comment]
Compiled from source on OpenFramework 0.11.2 but still getting same results where PID and VID are not able to be read.

![Screenshot 2023-06-30 at 11 25 45 AM](https://github.com/EmotiBit/ofxEmotiBit/assets/90929134/ff26b877-a453-47a6-a4b2-a89a16867ab6)

**Comment by nitin710** [comment]
- Looks like this has already been flagged as an issue here: https://github.com/bakercp/ofxSerial/issues/24
- ofxSerial uses Serial, whjich has this interesting issue: https://github.com/wjwwood/serial/issues/258
- This might offer a solution: https://github.com/wjwwood/serial/pull/271
