### ISSUE TITLE
Compilation issues with OF 11.2 - solved

### ISSUE THREAD

**Issue by tobiasweede** [EmotiBit/ofxEmotiBit#223]
Hi,

this is not a bug.
However, others might also be interested.
I try to compile the Oscilator for some time now.
It is definitely not straight forward.

I checkout out the branch fix-OFv0.11.2_2 and use the corresponding OF version.

![Visual Studio 2022 Errors](https://github.com/EmotiBit/ofxEmotiBit/assets/14060368/b4d9e7c7-f10c-45b8-bad5-ff2035e6b189)

Can someone give me some tips how I get the Oscillator running?

**Comment by nitin710** [comment]
Looks like an error with openframeworks dependency. 
You mentioned you are using the corresponding OF, i would double check that. The branch is compiling on Windows and I not seen this error before.

Can you share you the folder structure of your project(From OF_ROOT down to the project)? It might be that the EmotiBit Oscilloscope (and ofxEmotiBit) might not be in the right location and missing path to lib files from OF_ROOT.

**Comment by tobiasweede** [comment]
Thank you for the suggestions.
I re-ran the ofx library setup script and it seems to work now.
The library download might have been interrupted the first time without me noticing.

**Comment by nitin710** [comment]
Closing this issue.
