### ISSUE TITLE
LSL Renovations

### ISSUE THREAD

**Issue by badfishblues** [EmotiBit/ofxEmotiBit#9]
- Add double buffer to ofxLSL
- consider different stream types,
  - is it a problem?
  - is it acceptable to treat all as string?
  - is templating neccessary?
- handling stream names is currently hardcoded to ofxEmotiBit as  a static
  - look into handling it as a char * or std::string so each instance of ofxLSL can handle a stream
  - Eventually allow name input from GUI?
  - If not, from EmotiBit_example.ino?
- multiple streams?
- Parser to handle LSL

**Comment by nitin710** [comment]
LSL has changed a lot since this issue. marking as legacy
